---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: argocd-clusterrole
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-read-secrets-global
subjects:
- kind: ServiceAccount
  name: aws-load-balancer-controller # name of your service account
  namespace: kube-system # this is the namespace your service account is in
roleRef: # referring to your ClusterRole
  kind: ClusterRole
  name: argocd-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
data:
  clientID: NjJycW11aXFzajIxbWg0YTNmaGU1YWZvbjU=
  clientSecret: MjAxMnE0ZGlraGxvMWxxNHFmNDh2bG5lMHRkYnQxNmtkb2x2ZW5tYjdjNGNndG9tcGMw
kind: Secret
metadata:
  name: my-argocd-secret
  namespace: ${namespace}
  app.kubernetes.io/managed-by: Helm
  meta.helm.sh/release-name: ${argocd_name}
  meta.helm.sh/release-namespace: ${namespace}
type: Opaque

